version: '3.8'

services:
  # Aplicação FastAPI
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///./ecommerce.db
    volumes:
      - ./ecommerce.db:/app/ecommerce.db
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Aplicação Streamlit (mantida para compatibilidade)
  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=sqlite:///./ecommerce.db
    volumes:
      - ./ecommerce.db:/app/ecommerce.db
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    restart: unless-stopped
    depends_on:
      - app

  # Nginx (proxy reverso)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
      - streamlit
    restart: unless-stopped

volumes:
  app_data:
